### ISSUE TITLE
Error occurs when running the Test with 1 gpu.

### ISSUE THREAD

**Issue by Ahsan686** [ShenhanQian/KGDet#3]
I Followed all the instructions to install this repo but when i run Test with 1 gpu demo, follow error occurs.

Traceback (most recent call last):                                                                                                         File "./mmdetection/tools/test.py", line 13, in <module>                                                                                   from mmdet.apis import init_dist                                                                                                       File "/home/revolveai/projects/KGDet/mmdetection/mmdet/apis/__init__.py", line 2, in <module>                                              from .inference import (inference_detector, init_detector, show_result,                                                                File "/home/revolveai/projects/KGDet/mmdetection/mmdet/apis/inference.py", line 10, in <module>                                            from mmdet.core import get_classes                                                                                                     File "/home/revolveai/projects/KGDet/mmdetection/mmdet/core/__init__.py", line 3, in <module>                                              from .evaluation import *  # noqa: F401, F403                                                                                          File "/home/revolveai/projects/KGDet/mmdetection/mmdet/core/evaluation/__init__.py", line 5, in <module>                                   from .eval_hooks import (CocoDistEvalmAPHook, CocoDistEvalRecallHook,                                                                  File "/home/revolveai/projects/KGDet/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 13, in <module>                                from mmdet import datasets                                                                                                             File "/home/revolveai/projects/KGDet/mmdetection/mmdet/datasets/__init__.py", line 7, in <module>                                          from .loader import DistributedGroupSampler, GroupSampler, build_dataloader                                                            File "/home/revolveai/projects/KGDet/mmdetection/mmdet/datasets/loader/__init__.py", line 1, in <module>                                   from .build_loader import build_dataloader                                                                                             File "/home/revolveai/projects/KGDet/mmdetection/mmdet/datasets/loader/build_loader.py", line 8, in <module>                               from .sampler import DistributedGroupSampler, DistributedSampler, GroupSampler                                                         File "/home/revolveai/projects/KGDet/mmdetection/mmdet/datasets/loader/sampler.py", line 6, in <module>                                    from mmcv.runner.utils import get_dist_info                                                                                          ImportError: cannot import name 'get_dist_info'                                                                                          Traceback (most recent call last):                                                                                                         File "/home/revolveai/miniconda3/envs/pft_test/lib/python3.6/runpy.py", line 193, in _run_module_as_main                                   "__main__", mod_spec)                                                                                                                  File "/home/revolveai/miniconda3/envs/pft_test/lib/python3.6/runpy.py", line 85, in _run_code                                              exec(code, run_globals)                                                                                                                File "/home/revolveai/miniconda3/envs/pft_test/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>             main()                                                                                                                                 File "/home/revolveai/miniconda3/envs/pft_test/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main                 cmd=cmd)                                                                                                                             subprocess.CalledProcessError: Command '['/home/revolveai/miniconda3/envs/pft_test/bin/python', '-u', './mmdetection/tools/test.py', '--local_rank=0', 'configs/kgdet_moment_r50_fpn_1x-demo.py', 'checkpoints/KGDet_epoch-12.pth', '--launcher', 'pytorch', '--json_out', 'work_dirs/demo_KGDet.json', '--eval', 'bbox', 'keypoints']' returned non-zero exit status 1.

**Comment by ShenhanQian** [comment]
Please check if the version of `mmcv` is the same as the one in `requirements.txt`

**Comment by Ahsan686** [comment]
yes the error was because of mmcv version, thank you
